### PR TITLE
INclude operator query issue

### PR DESCRIPTION
**Pull request by kasthor**
Changing IN operator behavior so it outputs 'IN ( ?, ? )' instead of 'IN ?'

When on SqlserverAdapter it's necesary to prepare the queries in a different way when using the INclude operator. It actually throws an error on SqlserverAdapter

I'm unsure about compatibility issues with other Adapters

### CODE REVIEW

**Comment by dkubb** [comment]
@dbussink: is the contract in DO that for `IN()` clauses we just use `IN ?` and it will take care of expanding the raw string to the proper number of bind values, and parenthesize it? I think so, but I want to confirm first.

If so, then we probably should fix this as the do_sqlserver level and make sure it expands the same way as other drivers; shared specs will probably also be helpful to ensure other drivers have the same behaviour.

**Comment by dbussink** [comment]
The contract is indeed that IN ? should work. That means this should be fixed at the do_sqlserver level yeah

**Comment by kasthor** [comment]
may i know which contract are you referring to? so i can review it before trying a pull request?

then i will patch do_sqlserver instead thanks

**Comment by dkubb** [comment]
@kasthor: Oh, a contract not in the strong terms you might be thinking. It's just a short way of saying "the behaviour a component in the system should exhibit". In DO there is a library called data_objects that provides core functionality. People can write drivers for specific databases, and there are expectations from the rest of the system how they should behave. @dbussink has been writing shared specs to provide more assistance to  driver authors so they can be more certain their drivers are behaving as expected.

In this case the do_sqlserver was doing something unexpected with the bind values, something different from all the other DO drivers. Your patch was well intentioned, but would probably break when used with other DO drivers besides do_sqlserver.

What needs to happen is someone needs to update the do_sqlserver driver directly and make it so that when it gets `IN ?`, with the value being an Array, it would expand it to the appropriate `IN(val1, val2, val3)` expression and evaluate it.

**Pull request closed without merging**
